- app/uk/gov/hmrc/plasticpackagingtax/returns/controllers/returns/HumanMedicinesPlasticWeightController.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/forms/HumanMedicinesPlasticWeight.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/models/domain/HumanMedicinesPlasticWeight.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/human_medicines_plastic_weight_page.scala.html
- conf/messages.en
- conf/returns.routes
- test/uk/gov/hmrc/plasticpackagingtax/returns/builders/TaxReturnBuilder.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/controllers/returns/HumanMedicinesPlasticWeightControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/controllers/returns/ImportedPlasticWeightControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/forms/HumanMedicinesPlasticWeightSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/forms/ImportedPlasticWeightSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/HumanMedicinesPlasticWeightViewSpec.scala
> PPT-448: human medicines plastic weight page impl

- app/uk/gov/hmrc/plasticpackagingtax/returns/controllers/returns/CheckYourReturnController.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/controllers/returns/ConvertedPackagingCreditController.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/models/domain/MetaData.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/models/domain/TaxReturn.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/models/response/FlashKeys.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/check_your_return_page.scala.html
- conf/messages.en
- conf/returns.routes
- test/uk/gov/hmrc/plasticpackagingtax/returns/base/unit/UnitViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/controllers/returns/CheckYourReturnControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/controllers/returns/ConvertedPackagingCreditControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/CheckYourReturnViewSpec.scala
> PPTP-458: check your return page

- app/assets/javascripts/timeoutDialog.js
- app/uk/gov/hmrc/plasticpackagingtax/returns/config/AppConfig.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/config/TimeoutDialogConfig.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/controllers/home/SignOutController.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/views/components/govUkLink.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/returns/views/components/timeoutDialog.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/returns/views/home/session_timed_out.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/returns/views/main_template.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/returns/views/model/SignOutReason.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/views/partials/siteHeader.scala.html
- build.sbt
- conf/application.conf
- conf/home.routes
- conf/messages.en
- project/AppDependencies.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/base/unit/UnitViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/base/unit/ViewAssertions.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/controllers/home/SignOutControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/home/HomePageViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/home/SessionTimedOutViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/model/SignOutReasonSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/ExportedPlasticWeightViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/HumanMedicinesPlasticWeightViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/ImportedPlasticWeightViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/ManufacturedPlasticWeightViewSpec.scala
Also added the Exit Survey.
Nothing else but a copy and paste from the PPT Registration service.
> PPTP-572 Add Timeout config and signout link

- app/assets/stylesheets/_ppt.scss
- app/uk/gov/hmrc/plasticpackagingtax/returns/controllers/returns/CheckYourReturnController.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/controllers/returns/ConfirmationController.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/views/components/bulletList.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/confirmation_page.scala.html
- conf/messages.en
- conf/returns.routes
- tampermonkey/PPT_Returns_AutoComplete.js
- test/uk/gov/hmrc/plasticpackagingtax/returns/controllers/returns/CheckYourReturnControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/controllers/returns/ConfirmationControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/ConfirmationViewSpec.scala
- alerts are about links pointing to same url, so can be ignored for now, will tackle some of those links in other story
> PPTP-461: submission confirmation page

- app/uk/gov/hmrc/plasticpackagingtax/returns/views/main_template.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/returns/views/model/BackButton.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/check_your_return_page.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/converted_packaging_credit_page.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/exported_plastic_weight_page.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/human_medicines_plastic_weight_page.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/imported_plastic_weight_page.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/manufactured_plastic_weight_page.scala.html
- conf/messages.en
> PPTP-579: added back link accessibility text

- app/uk/gov/hmrc/plasticpackagingtax/returns/views/components/saveAndContinue.scala.html
> PPTP-576: fix for accessibility issues on save button

- app/uk/gov/hmrc/plasticpackagingtax/returns/controllers/returns/ManufacturedPlasticWeightController.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/forms/ManufacturedPlasticWeight.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/models/domain/ManufacturedPlasticWeight.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/models/domain/TaxReturn.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/utils/TaxLiability.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/check_your_return_page.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/manufactured_plastic_weight_page.scala.html
- conf/messages.en
- tampermonkey/PPT_Returns_AutoComplete.js
- test/uk/gov/hmrc/plasticpackagingtax/returns/builders/TaxReturnBuilder.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/controllers/returns/CheckYourReturnControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/controllers/returns/ManufacturedPlasticWeightControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/forms/ManufacturedPlasticWeightSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/models/dmoain/TaxReturnSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/utils/TaxLiabilityFactoryTest.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/CheckYourReturnViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/ManufacturedPlasticWeightViewSpec.scala
Warning on underlined link (no action required there)
> PPTP-814: removed totalKgBelowThreshold field from manufactured pp page

- app/uk/gov/hmrc/plasticpackagingtax/returns/controllers/returns/ExportedPlasticWeightController.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/forms/CommonFormValidators.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/forms/ExportedPlasticWeight.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/forms/ManufacturedPlasticWeight.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/models/domain/ExportedPlasticWeight.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/models/domain/TaxReturn.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/utils/TaxLiability.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/check_your_return_page.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/exported_plastic_weight_page.scala.html
- build.sbt
- conf/messages.en
- tampermonkey/PPT_Returns_AutoComplete.js
- test/uk/gov/hmrc/plasticpackagingtax/returns/builders/TaxReturnBuilder.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/config/ErrorHandlerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/controllers/returns/CheckYourReturnControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/controllers/returns/ExportedPlasticWeightControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/forms/CommonFormValidatorsSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/forms/ExportedPlasticWeightSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/forms/ManufacturedPlasticWeightSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/forms/RecycledPlasticWeightSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/models/dmoain/TaxReturnSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/utils/TaxLiabilityFactoryTest.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/CheckYourReturnViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/ExportedPlasticWeightViewSpec.scala
> PPTP-817: removed credit export field

- README.md
- tampermonkey/PPT_Returns_Auth_AutoComplete.js
Also updated the `README.md` file.
> PPTP-925 'QuickButton' style position is 'absolute'

- app/uk/gov/hmrc/plasticpackagingtax/returns/models/subscription/LegalEntityDetails.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/models/subscription/Subscription.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/models/subscription/group/GroupOrPartnershipDetails.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/models/subscription/group/GroupOrPartnershipSubscription.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/models/subscription/subscriptionDisplay/SubscriptionDisplayResponse.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/models/subscription/subscriptionUpdate/SubscriptionUpdateRequest.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/base/PptTestData.scala
> PPTP-1124 Changes for API spec update

- README.md
- app/uk/gov/hmrc/plasticpackagingtax/returns/views/subscriptions/view_subscription_page.scala.html
Remove duplicate `primary-contact-details` id
> PPTP-1200 - Duplicate IDs used on Review Registration screen

- tampermonkey/PPT_Returns_Auth_AutoComplete.js
Update `Quick Submit` button in Tampermonkey scripts and bump the file version.
Solution provided by @SteveSugden: https://hmrcdigital.slack.com/archives/G01PR65H61W/p1632299076040300
> BAU: Update Quick Submit button Tampermonkey script

- test/uk/gov/hmrc/plasticpackagingtax/returns/base/unit/UnitViewSpec.scala
Add a validating message api for tests to check that message keys are defined
> BAU - validating test message api

- test/uk/gov/hmrc/plasticpackagingtax/returns/spec/ViewMatchers.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/home/HomePageViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/home/SessionTimedOutViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/home/UnauthorisedViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/home/ViewSubscriptionViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/CheckYourReturnViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/ConfirmationViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/ConvertedPackagingCreditViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/ExportedPlasticWeightViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/HumanMedicinesPlasticWeightViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/ImportedPlasticWeightViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/ManufacturedPlasticWeightViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/RecycledPlasticWeightViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/ReturnsInformationPageViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/StartPageViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/subscriptions/PrimaryContactNameViewSpec.scala
> BAU-updated-view-tests Removed messages validation

- project/AppDependencies.scala
Done by updating to bootstrap-play 5.16
> PPTP-1322 - Stop unnecessary asset auditing

- app/uk/gov/hmrc/plasticpackagingtax/returns/connectors/SubscriptionConnector.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/connectors/TaxReturnsConnector.scala
> PPTP-1379 Additional info level logging

- tampermonkey/PPT_Returns_Auth_AutoComplete.js
Bumped Tampermonkey script version for automatic script download for `EtmpRegistrationNumber` change.
> BAU: Bump Tampermonkey script version for EtmpRegistrationNumber changes

- project/AppDependencies.scala
- project/plugins.sbt
> BAU - update dependencies

- app/uk/gov/hmrc/plasticpackagingtax/returns/config/AppConfig.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/models/subscription/subscriptionDisplay/SubscriptionDisplayResponse.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/views/home/home_page.scala.html
- conf/messages.en
- test/uk/gov/hmrc/plasticpackagingtax/returns/models/subscription/subscriptionDisplay/SubscriptionDisplayResponseSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/home/HomePageViewSpec.scala
ATs: https://github.com/hmrc/plastic-packaging-tax-acceptance/pull/93
> PPTP-1656 : Refactor PPT Dashboard

- app/uk/gov/hmrc/plasticpackagingtax/returns/config/AppConfig.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/views/home/home_page.scala.html
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/home/HomePageViewSpec.scala
> PPTP-1692 : Fix Manage Partners Link on Dash

- app/uk/gov/hmrc/plasticpackagingtax/returns/config/AppConfig.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/views/home/unauthorised.scala.html
- conf/application.conf
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/home/UnauthorisedViewSpec.scala
> PPTP-1618_links

- README.md
- app/uk/gov/hmrc/plasticpackagingtax/returns/config/AppConfig.scala
- conf/app.routes
- conf/application.conf
- tampermonkey/PPT_Returns_Auth_AutoComplete.js
- tampermonkey/PPT_Returns_AutoComplete.js
- test/uk/gov/hmrc/plasticpackagingtax/returns/connectors/TaxReturnsConnectorSpec.scala
Updating submit returns url
Dependencies:
- https://github.com/hmrc/app-config-base/pull/6843
- https://github.com/hmrc/plastic-packaging-tax-returns/pull/57
> PPTP-1755 - updating submit returns url

- app/uk/gov/hmrc/plasticpackagingtax/returns/controllers/returns/ImportedPlasticWeightController.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/controllers/returns/ManufacturedPlasticWeightController.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/forms/CommonFormValidators.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/forms/CommonFormValues.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/forms/ImportedPlastic.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/models/domain/TaxReturn.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/views/components/Styles.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/check_your_return_page.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/human_medicines_plastic_weight_page.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/imported_plastic_page.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/imported_plastic_weight_page.scala.html
- conf/messages.en
- conf/returns.routes
- test/uk/gov/hmrc/plasticpackagingtax/returns/base/unit/ControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/base/unit/MockJourneyAction.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/connectors/TaxReturnsConnectorSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/controllers/returns/ImportedPlasticWeightControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/controllers/returns/ManufacturedPlasticWeightControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/models/dmoain/TaxReturnSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/models/request/JourneyActionSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/CheckYourReturnViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/HumanMedicinesPlasticWeightViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/ImportedPlasticPageViewSpec.scala
> PPTP-1647 Imported plastic

- README.md
> Update readme with new urls

- app/uk/gov/hmrc/plasticpackagingtax/returns/audit/CreateTaxReturnEvent.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/config/AppConfig.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/connectors/TaxReturnsConnector.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/controllers/returns/CheckYourReturnController.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/models/domain/ReturnType.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/models/domain/TaxReturn.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/base/unit/MockTaxReturnsConnector.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/builders/TaxReturnBuilder.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/connectors/TaxReturnsConnectorSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/controllers/returns/CheckYourReturnControllerSpec.scala
Check and save your answer triggers submit on backend.
Marks return as type NEW.
> PPTP-1776 Call submit new return

- app/uk/gov/hmrc/plasticpackagingtax/returns/controllers/actions/AuthAction.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/base/MockAuthAction.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/controllers/actions/AuthActionSpec.scala
Reverts hmrc/plastic-packaging-tax-returns-frontend#111
This will not work as it stands.
> Revert "PPTP-1762 - Agents with delegated access can access Plastics Returns"

- tampermonkey/PPT_Returns_Auth_AutoComplete.js
- tampermonkey/PPT_Returns_AutoComplete.js
Check the paths.
Added 2 new pages to the quick submit path.
Tested against latest sm versions.
> Restore Returns tamper monkey sign in and quick submit

- app/uk/gov/hmrc/plasticpackagingtax/returns/views/home/home_page.scala.html
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/home/HomePageViewSpec.scala
> PPTP-1792 Removed return dates link from returns tile

- app/uk/gov/hmrc/plasticpackagingtax/returns/controllers/home/HomeController.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/views/home/home_page.scala.html
- test/uk/gov/hmrc/plasticpackagingtax/returns/controllers/home/HomeControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/home/HomePageViewSpec.scala
> PPTP-1808 | remove journey action from home page

- app/uk/gov/hmrc/plasticpackagingtax/returns/config/AppConfig.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/connectors/FinancialsConnector.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/controllers/home/HomeController.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/models/financials/PPTFinancials.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/views/home/home_page.scala.html
- conf/messages.en
- test/uk/gov/hmrc/plasticpackagingtax/returns/connectors/FinancialsConnectorSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/controllers/home/HomeControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/models/domain/TaxReturnSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/models/financials/PPTFinancialsSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/home/HomePageViewSpec.scala
> PPTP-419 View payment due date & amount due

- app/uk/gov/hmrc/plasticpackagingtax/returns/models/financials/PPTFinancials.scala
- conf/messages.en
> PPTP-419 Content changes

- app/uk/gov/hmrc/plasticpackagingtax/returns/utils/TaxLiability.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/models/domain/TaxReturnSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/utils/TaxLiabilityFactoryTest.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/CheckYourReturnViewSpec.scala
> PPTP-1865 : Fix FE Tax Return Calcs

- app/uk/gov/hmrc/plasticpackagingtax/returns/controllers/bta/BtaEntryPointController.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/controllers/returns/SubmittedReturnsController.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/submitted_returns_page.scala.html
- conf/app.routes
- conf/messages.en
- conf/returns.routes
- test/uk/gov/hmrc/plasticpackagingtax/returns/controllers/bta/BtaEntryPointControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/controllers/returns/SubmittedReturnsControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/SubmittedReturnsViewSpec.scala
> PPTP-1839 : New Submitted Returns Page

- app/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/submitted_returns_page.scala.html
- conf/messages.en
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/SubmittedReturnsViewSpec.scala
> Pptp 1779 submitted returns 2

- app/uk/gov/hmrc/plasticpackagingtax/returns/controllers/actions/FormAction.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/views/agents/agents_page.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/returns/views/components/continue.scala.html
- conf/messages.en
- test/uk/gov/hmrc/plasticpackagingtax/returns/base/unit/ControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/controllers/returns/CheckYourReturnControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/controllers/returns/ConvertedPackagingCreditControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/controllers/returns/ExportedPlasticWeightControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/controllers/returns/HumanMedicinesPlasticWeightControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/controllers/returns/RecycledPlasticWeightControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/controllers/returns/StartDateReturnControllerTest.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/controllers/subscriptions/ViewSubscriptionControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/CheckYourReturnViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/ConvertedPackagingCreditViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/ExportedPlasticWeightViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/HumanMedicinesPlasticWeightViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/ImportedPlasticPageViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/ImportedPlasticWeightViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/ManufacturedPlasticViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/ManufacturedPlasticWeightViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/RecycledPlasticWeightViewSpec.scala
Back fill agents landing page copy supplied by Content.
Adding Continue button = big files diff.
> Pptp 1797 agents content

- app/uk/gov/hmrc/plasticpackagingtax/returns/controllers/actions/AuthAction.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/controllers/actions/AuthAgentAction.scala
- build.sbt
- test/uk/gov/hmrc/plasticpackagingtax/returns/controllers/returns/StartDateReturnControllerTest.scala
Unused / reused import
Coverage nudge.
> Post merge clean up - build fix

- app/uk/gov/hmrc/plasticpackagingtax/returns/config/AppConfig.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/views/home/home_page.scala.html
- conf/messages.en
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/home/HomePageViewSpec.scala
PPTP-508: added de-reg link to the home page
> PPTP-508: added de-reg link to the home page

- conf/messages.en
> feature/PPTP-1873 | Remove the word the from start link

- app/controllers/AmendAreYouSureController.scala
- app/forms/AmendAreYouSureFormProvider.scala
- app/pages/AmendAreYouSurePage.scala
- app/viewmodels/checkAnswers/AmendAreYouSureSummary.scala
- app/views/AmendAreYouSureView.scala.html
- conf/app.routes
- conf/messages.en
- migrations/applied_migrations/AmendAreYouSure.sh
- test-utils/generators/PageGenerators.scala
- test-utils/generators/UserAnswersEntryGenerators.scala
- test-utils/generators/UserAnswersGenerator.scala
- test/controllers/AmendAreYouSureControllerSpec.scala
- test/forms/AmendAreYouSureFormProviderSpec.scala
- test/pages/AmendAreYouSurePageSpec.scala
> Added start page - are you sure

- app/config/Module.scala
- app/controllers/AmendAreYouSureController.scala
- app/controllers/AmendDirectExportPlasticPackagingController.scala
- app/controllers/AmendHumanMedicinePlasticPackagingController.scala
- app/controllers/AmendImportedPlasticPackagingController.scala
- app/controllers/AmendManufacturedPlasticPackagingController.scala
- app/controllers/AmendRecycledPlasticPackagingController.scala
- app/controllers/CheckYourAnswersController.scala
- app/controllers/actions/DataRequiredAction.scala
- app/forms/AmendAreYouSureFormProvider.scala
- app/models/requests/DataRequest.scala
- app/navigation/Navigator.scala
- app/pages/AmendAreYouSurePage.scala
- app/viewmodels/checkAnswers/AmendAreYouSureSummary.scala
- app/viewmodels/checkAnswers/AmendDirectExportPlasticPackagingSummary.scala
- app/viewmodels/checkAnswers/AmendHumanMedicinePlasticPackagingSummary.scala
- app/viewmodels/checkAnswers/AmendImportedPlasticPackagingSummary.scala
- app/viewmodels/checkAnswers/AmendManufacturedPlasticPackagingSummary.scala
- app/viewmodels/checkAnswers/AmendRecycledPlasticPackagingSummary.scala
- app/viewmodels/checkAnswers/SummaryViewModel.scala
- app/views/AmendAreYouSureView.scala.html
- app/views/CheckYourAnswersView.scala.html
- build.sbt
- test/controllers/AmendAreYouSureControllerSpec.scala
- test/controllers/AmendManufacturedPlasticPackagingControllerSpec.scala
- test/forms/AmendAreYouSureFormProviderSpec.scala
- test/navigation/NavigatorSpec.scala
- test/pages/AmendAreYouSurePageSpec.scala
-Navigator wired in
-yes/no page logic added
-Trait added for refactor
-Tests added and passing
> Scaffold navigation

- app/uk/gov/hmrc/plasticpackagingtax/returns/config/AppConfig.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/config/Features.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/controllers/home/HomeController.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/views/home/home_page.scala.html
- conf/application.conf
- test/uk/gov/hmrc/plasticpackagingtax/returns/controllers/home/HomeControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/home/HomePageViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/RecycledPlasticWeightViewSpec.scala
> Pptp 1903 feature switch for april go live

- conf/messages.cy
> PPTP-1237 - Adding initial Welsh translations and placeholder text

- app/connectors/TaxReturnsConnector.scala
- app/controllers/AmendAreYouSureController.scala
- app/controllers/ViewReturnSummaryController.scala
- app/controllers/helpers/TaxReturnHelper.scala
- app/navigation/Navigator.scala
- app/views/AmendAreYouSureView.scala.html
- app/views/ViewUtils.scala
- app/views/componants/ReturnsSectionHeading.scala.html
- conf/messages.en
- test-utils/views/ViewUtilsTest.scala
- test/controllers/AmendAreYouSureControllerSpec.scala
- test/navigation/NavigatorSpec.scala
ReturnsSubheading: this + related ported from main
messages:
-error messages updated
areyousure:
-navigates to viewReturnSummary on No
-currently only subHeading that populates return period
> Scaffold amend views

- app/config/FrontendAppConfig.scala
- app/connectors/FinancialsConnector.scala
- app/controllers/IndexController.scala
- app/controllers/MakePaymentController.scala
- app/models/financials/PPTFinancials.scala
- app/views/IndexView.scala.html
- conf/app.routes
- conf/application.conf
- conf/messages.en
- test/base/utils/ConnectorISpec.scala
- test/connectors/FinancialsConnectorSpec.scala
- test/controllers/MakePaymentControllerSpec.scala
- test/models/financials/PPTFinancialsSpec.scala
> PPTP-1763 | Payment redirect link construction

- app/controllers/DeregisteredController.scala
- app/controllers/ReturnsCheckYourAnswersController.scala
- conf/messages.en
> Scaffold to staging - green build

- app/views/ReturnConfirmationView.scala.html
- conf/application.conf
Updating link to call feedback service
> PPTP-2024 - Fixing exit survey link

- app/views/IndexView.scala.html
- conf/messages.en
> PPTP-2020: Removed payment history link

- app/controllers/ViewReturnSummaryController.scala
- test/controllers/ViewReturnSummaryControllerSpec.scala
> PPTP-2019 | verify period key is correct format

- app/controllers/ConvertedPackagingCreditController.scala
- app/forms/ConvertedPackagingCreditFormProvider.scala
- test/controllers/ConvertedPackagingCreditControllerSpec.scala
- test/forms/ConvertedPackagingCreditFormProviderSpec.scala
> PPTP-2016 | make form take amount as maximum

- app/config/FrontendAppConfig.scala
- app/controllers/MakePaymentController.scala
- conf/application.conf
- test/controllers/MakePaymentControllerSpec.scala
> PPTP-2023 | Fix payment journey in staging

- app/config/FrontendAppConfig.scala
- conf/application.conf
> Fix feedback beta banner

- app/config/FrontendAppConfig.scala
- conf/application.conf
> Correctly pull in contact front end base url

- app/controllers/actions/AuthFunction.scala
- app/controllers/actions/IdentifierAction.scala
> Revert accidental changes

- app/assets/stylesheets/_returns.scss
- app/config/FrontendAppConfig.scala
- app/views/templates/Layout.scala.html
- conf/application.conf
> Add UR banner

- app/config/FrontendAppConfig.scala
- app/controllers/auth/AuthController.scala
- app/views/UnauthorisedView.scala.html
- conf/application.conf
- conf/messages.en
- test/base/FakeAuthActionNotEnrolled.scala
- test/base/SpecBase.scala
- test/controllers/auth/AuthControllerSpec.scala
> PPTP-2105 - Fix the sign out issue for users with no enrolments

- app/config/FrontendAppConfig.scala
- app/views/DeregisteredView.scala.html
- conf/messages.en
> Add BTA link to deregisetred view

- app/config/FrontendAppConfig.scala
- app/views/ImportedPlasticPackagingView.scala.html
- app/views/ImportedPlasticPackagingWeightView.scala.html
- app/views/templates/Layout.scala.html
- conf/messages.cy
- conf/messages.en
> Update with latest content change in SOT

- test/forms/behaviours/LongFieldBehaviours.scala
Commented out 2 tests we're working on to get build back in the meantime
> Quick fix - tmp remove 2 tests

- app/pages/ManufacturedPlasticPackagingPage.scala
- app/pages/ManufacturedPlasticPackagingWeightPage.scala
- conf/messages.cy
- conf/messages.en
- Updating CYA row to show 0kg if the user answers no to the "Manufactured plastic" question
- Adding placeholder translations to Welsh message file
- Updating caption casing
> PPTP-1968 - Updating CYA behaviour if no manufactured plastic

- test/forms/behaviours/LongFieldBehaviours.scala
Proper fix for 2 intermittently failing tests
> Fix iffy tests

- app/views/returns/ExportedPlasticPackagingWeightView.scala.html
- conf/messages.cy
- conf/messages.en
- test/views/returns/ExportedPlasticPackagingWeightViewSpec.scala
Updating content and specs following review comments in [PPTP-1649](https://jira.tools.tax.service.gov.uk/browse/PPTP-1649)
> PPTP-1649 - Updating content and specs

- app/views/returns/ReturnConfirmationView.scala.html
- conf/app.routes
- conf/messages.en
- test/views/returns/ReturnConfirmationViewSpec.scala
> Content updates for first pass of return submit - confirmation page

- app/views/returns/SubmittedReturnsView.scala.html
- test/views/returns/SubmittedReturnsViewSpec.scala
Fix link alignment
Before:
After:
> PPTP-2183 - Updating link alignment

- app/views/returns/ReturnConfirmationView.scala.html
- conf/messages.cy
- conf/messages.en
> bold the charge reference number

- app/viewmodels/checkAnswers/returns/PlasticPackagingTotalSummary.scala
- app/views/ViewUtils.scala
- app/views/returns/ReturnsCheckYourAnswersView.scala.html
> Totals bold

- conf/messages.cy
Adding missing Welsh message keys
> Adding Welsh message keys

- app/models/financials/PPTFinancials.scala
- test/models/financials/PPTFinancialsSpec.scala
> PPTP-1916 | change model

- app/config/Features.scala
- app/config/FrontendAppConfig.scala
- app/controllers/amends/CheckYourAnswersController.scala
- app/views/amends/ViewReturnSummaryView.scala.html
- conf/application.conf
- test/controllers/amends/CheckYourAnswersControllerSpec.scala
When feature is disabled:
-'amend your return' link on viewReturnSummary
-attempting to load checkYourAnswers page will redirect to account
> PPTP-2240: Feature switch for amends added

- app/controllers/helpers/TaxReturnViewModel.scala
- app/controllers/returns/ReturnsCheckYourAnswersController.scala
- app/views/returns/ReturnsCheckYourAnswersView.scala.html
- conf/messages.cy
- conf/messages.en
> PPTP-2264 | remove submit button for bad return

- app/controllers/JourneyRecoveryController.scala
- app/controllers/actions/DataRequiredAction.scala
- app/views/JourneyRecoveryView.scala.html
- conf/app.routes
- conf/messages.cy
- conf/messages.en
- test/base/ViewSpecBase.scala
- test/controllers/JourneyRecoveryControllerSpec.scala
- test/controllers/amends/AmendAreYouSureControllerSpec.scala
- test/controllers/amends/AmendDirectExportPlasticPackagingControllerSpec.scala
- test/controllers/amends/AmendHumanMedicinePlasticPackagingControllerSpec.scala
- test/controllers/amends/AmendImportedPlasticPackagingControllerSpec.scala
- test/controllers/amends/AmendManufacturedPlasticPackagingControllerSpec.scala
- test/controllers/amends/AmendRecycledPlasticPackagingControllerSpec.scala
- test/controllers/amends/CheckYourAnswersControllerSpec.scala
- test/controllers/returns/ConvertedPackagingCreditControllerSpec.scala
- test/controllers/returns/DirectlyExportedComponentsControllerSpec.scala
- test/controllers/returns/ExportedPlasticPackagingWeightControllerSpec.scala
- test/controllers/returns/ImportedPlasticPackagingControllerSpec.scala
- test/controllers/returns/ImportedPlasticPackagingWeightControllerSpec.scala
- test/controllers/returns/ManufacturedPlasticPackagingControllerSpec.scala
- test/controllers/returns/ManufacturedPlasticPackagingWeightControllerSpec.scala
- test/controllers/returns/NonExportedHumanMedicinesPlasticPackagingControllerSpec.scala
- test/controllers/returns/NonExportedHumanMedicinesPlasticPackagingWeightControllerSpec.scala
- test/controllers/returns/NonExportedRecycledPlasticPackagingControllerSpec.scala
- test/controllers/returns/NonExportedRecycledPlasticPackagingWeightControllerSpec.scala
- test/controllers/returns/ReturnsCheckYourAnswersControllerSpec.scala
- test/views/JourneyRecoveryViewSpec.scala
> PPTP-2239: add content for the journey recovery view

- conf/messages.cy
- Includes keys to fix https://jira.tools.tax.service.gov.uk/browse/PPTP-2239
- Includes additional keys for work on CYA page (block submission and change links)
> PPTP-2239 - Adding welsh messages for return to PPT account

- app/views/IndexView.scala.html
- conf/messages.cy
- conf/messages.en
- test/controllers/TaxReturnBuilder.scala
> PPTP-2240 | toggle content with amendsToggle

- app/views/templates/Layout.scala.html
> PPTP-2141 - passing language to ReportTechnicalIssue

- conf/app.routes
> Added BTA endpoints

- conf/messages.cy
> remove duplicate kg from heading

- conf/messages.cy
Content described in ticket https://jira.tools.tax.service.gov.uk/browse/PPTP-2292
> PPTP-2292 - Welsh translations

- build.sbt
> PPT Returns FE Major version bump to 1

- app/controllers/helpers/TaxReturnHelper.scala
- app/controllers/returns/StartYourReturnController.scala
- test/controllers/returns/StartYourReturnControllerSpec.scala
> Bounce users with no obligation away from returns to home page

- app/controllers/returns/ReturnsCheckYourAnswersController.scala
- app/controllers/returns/StartYourReturnController.scala
- app/views/IndexView.scala.html
> widen toggle for returns enabled

- app/views/returns/ImportedPlasticPackagingView.scala.html
- app/views/returns/ManufacturedPlasticPackagingView.scala.html
- app/views/returns/NonExportedRecycledPlasticPackagingView.scala.html
> Links to open in same tab

- app/controllers/amends/ViewReturnSummaryController.scala
- app/controllers/returns/StartYourReturnController.scala
- app/viewmodels/checkAnswers/ViewReturnSummaryViewModel.scala
- app/viewmodels/checkAnswers/amends/AmendDirectExportPlasticPackagingSummary.scala
- app/viewmodels/checkAnswers/amends/AmendHumanMedicinePlasticPackagingSummary.scala
- app/viewmodels/checkAnswers/amends/AmendManufacturedPlasticPackagingSummary.scala
- app/viewmodels/package.scala
- app/views/ViewUtils.scala
- app/views/amends/ViewReturnSummaryView.scala.html
- conf/messages.cy
- conf/messages.en
- test/controllers/ViewReturnSummaryControllerSpec.scala
- test/viewmodels/ViewReturnSummaryViewModelSpec.scala
TODO:
- update page URL to be dynamic
Amend Disabled (English):
Amend Disabled (Welsh):
Amend Enabled (English):
Amend Enabled (Welsh):
> PPTP-2313 - Content and format update following UCD review

- app/controllers/amends/SubmittedReturnsController.scala
- app/views/components/TaxReturnLink.scala.html
- app/views/returns/SubmittedReturnsView.scala.html
- conf/app.routes
- conf/messages.cy
- conf/messages.en
- test/controllers/returns/SubmittedReturnsControllerSpec.scala
- test/views/returns/SubmittedReturnsViewSpec.scala
See scope of the issue PPTP-2302 for "Update page 1: 'View submitted returns'". Note "Page 2" changes have already been done as part of PPTP-2313.
> PPTP-2302: Updated returns view for amend returns

- app/controllers/IndexController.scala
- app/models/EisFailure.scala
- test/controllers/IndexControllerSpec.scala
> Handle if Error doesnt look as expected

- app/viewmodels/govuk/InputFluency.scala
- app/viewmodels/govuk/RadiosFluency.scala
- app/views/returns/DirectlyExportedComponentsView.scala.html
- app/views/returns/ExportedPlasticPackagingWeightView.scala.html
- app/views/returns/ImportedPlasticPackagingView.scala.html
- app/views/returns/ImportedPlasticPackagingWeightView.scala.html
- app/views/returns/ManufacturedPlasticPackagingView.scala.html
- app/views/returns/ManufacturedPlasticPackagingWeightView.scala.html
- app/views/returns/NonExportedHumanMedicinesPlasticPackagingView.scala.html
- app/views/returns/NonExportedRecycledPlasticPackagingView.scala.html
- app/views/returns/NonExportedRecycledPlasticPackagingWeightView.scala.html
- app/views/returns/StartYourReturnView.scala.html
- test/views/returns/DirectlyExportedComponentsViewSpec.scala
- test/views/returns/ExportedPlasticPackagingWeightViewSpec.scala
- test/views/returns/NonExportedHumanMedicinesPlasticPackagingViewSpec.scala
- test/views/returns/NonExportedRecycledPlasticPackagingWeightViewSpec.scala
> PPTP-2383: fixing accessibility bug

- app/views/amends/AmendManufacturedPlasticPackagingView.scala.html
> Remove redundant aria describe by

- app/audit/Auditor.scala
- app/audit/returns/AmendStarted.scala
- app/audit/returns/GetExportCreditsFailure.scala
- app/audit/returns/GetExportCreditsSuccess.scala
- app/audit/returns/GetFulfilledObligationsFailure.scala
- app/audit/returns/GetFulfilledObligationsSuccess.scala
- app/audit/returns/GetOpenObligationsFailure.scala
- app/audit/returns/GetOpenObligationsSuccess.scala
- app/audit/returns/GetPaymentStatementFailure.scala
- app/audit/returns/GetPaymentStatementSuccess.scala
- app/audit/returns/GetReturnFailure.scala
- app/audit/returns/GetReturnSuccess.scala
- app/audit/returns/ReturnStarted.scala
- app/audit/returns/SubmitAmendFailure.scala
- app/audit/returns/SubmitAmendSuccess.scala
- app/audit/returns/SubmitReturnFailure.scala
- app/audit/returns/SubmitReturnSuccess.scala
> Added audit events package should we wish to take the events forward

- app/navigation/ReturnsJourneyNavigator.scala
- test/navigation/ReturnsJourneyNavigatorSpec.scala
> Pptp 2478 - fixing regression bug

- app/models/amends/AmendSummaryRow.scala
- app/viewmodels/checkAnswers/amends/AmendDirectExportPlasticPackagingSummary.scala
- app/viewmodels/checkAnswers/amends/AmendHumanMedicinePlasticPackagingSummary.scala
- app/viewmodels/checkAnswers/amends/AmendImportedPlasticPackagingSummary.scala
- app/viewmodels/checkAnswers/amends/AmendManufacturedPlasticPackagingSummary.scala
- app/viewmodels/checkAnswers/amends/AmendRecycledPlasticPackagingSummary.scala
- app/views/components/AmendsCyaTable.scala.html
- conf/messages.cy
- conf/messages.en
- test/controllers/amends/CheckYourAnswersControllerSpec.scala
Also Id's for AT's so they dont click by content
still todo is the empty boxes, waiting on content
> PPTP-2513 | accesible links on table

- app/config/FrontendAppConfig.scala
- app/connectors/TaxReturnsConnector.scala
- app/controllers/amends/CheckYourAnswersController.scala
- app/controllers/helpers/TaxReturnViewModel.scala
- app/controllers/returns/ReturnsCheckYourAnswersController.scala
- app/models/returns/Calculations.scala
- app/models/returns/ReturnDisplayApi.scala
- app/viewmodels/checkAnswers/ViewReturnSummaryViewModel.scala
- app/viewmodels/checkAnswers/amends/AmendDirectExportPlasticPackagingSummary.scala
- app/viewmodels/checkAnswers/amends/AmendHumanMedicinePlasticPackagingSummary.scala
- app/viewmodels/checkAnswers/amends/AmendImportedPlasticPackagingSummary.scala
- app/viewmodels/checkAnswers/amends/AmendManufacturedPlasticPackagingSummary.scala
- app/viewmodels/checkAnswers/amends/AmendRecycledPlasticPackagingSummary.scala
- app/viewmodels/package.scala
- app/views/amends/CheckYourAnswersView.scala.html
- app/views/components/AmendsCyaTable.scala.html
- conf/messages.cy
- conf/messages.en
- test/connectors/TaxReturnsConnectorSpec.scala
- test/controllers/amends/CheckYourAnswersControllerSpec.scala
- test/controllers/returns/ReturnsCheckYourAnswersControllerSpec.scala
- test/viewmodels/ViewmodelsSpec.scala
> Amends calc

- a11y/views/amends/AmendConfirmationA11ySpec.scala
- conf/messages.cy
- conf/messages.en
- test/views/amends/AmendConfirmationViewSpec.scala
> added charge reference text

- app/views/amends/CancelAmendView.scala.html
- conf/messages.cy
- conf/messages.en
- test/views/amends/CancelAmendViewSpec.scala
- welsh updates
-cancelAmend title now include year of period
-cancelAmend not provided error key added (no welsh yet)
> PPTP-2473: updates following content sweep: welsh, year added to cancelAmend title

- app/views/components/SectionH2Heading.scala.html
> fixing id problem

- a11y/views/AmendReturnA11ySpec.scala
- a11y/views/amends/CancelAmendViewA11ySpec.scala
- app/config/FrontendAppConfig.scala
- app/connectors/TaxReturnsConnector.scala
- app/controllers/amends/CheckYourAnswersController.scala
- app/controllers/amends/ViewReturnSummaryController.scala
- app/models/returns/DDInProgressApi.scala
- app/views/amends/ViewReturnSummaryView.scala.html
- conf/messages.cy
- conf/messages.en
- test/connectors/TaxReturnsConnectorSpec.scala
- test/controllers/ViewReturnSummaryControllerSpec.scala
> PPTP-2152 | FE stop user from clicking link to amend when DD due

- app/views/amends/AmendConfirmation.scala.html
- conf/messages.cy
- conf/messages.en
- test/views/amends/AmendConfirmationViewSpec.scala
> PPTP-2481: chargeRef number in bold now

- app/config/Features.scala
- app/controllers/IndexController.scala
- app/controllers/returns/ReturnsCheckYourAnswersController.scala
- app/controllers/returns/StartYourReturnController.scala
- app/views/IndexView.scala.html
- app/views/returns/ReturnsCheckYourAnswersView.scala.html
- conf/application.conf
- test/controllers/IndexControllerSpec.scala
- test/controllers/returns/ReturnsCheckYourAnswersControllerSpec.scala
- test/controllers/returns/StartYourReturnControllerSpec.scala
> PPTP-2514 | feature toggle in place ready for credits work

- a11y/views/ConfirmPlasticCreditViewA11ySpec.scala
- app/config/FrontendAppConfig.scala
- app/connectors/CalculateCreditsConnector.scala
- app/controllers/returns/credits/ConfirmPackagingCreditController.scala
- app/forms/returns/credits/ConvertedCreditsFormProvider.scala
- app/forms/returns/credits/ExportedCreditsFormProvider.scala
- app/models/CreditBalance.scala
- app/views/returns/credits/ConfirmPackagingCreditView.scala.html
- conf/app.routes
- conf/messages.cy
- conf/messages.en
- test/base/utils/ConnectorISpec.scala
- test/base/utils/WiremockTestServer.scala
- test/connectors/CalculateCreditsConnectorSpec.scala
- test/connectors/FinancialsConnectorSpec.scala
- test/connectors/ObligationsConnectorSpec.scala
- test/connectors/SubscriptionConnectorSpec.scala
- test/connectors/TaxReturnsConnectorSpec.scala
- test/controllers/returns/credits/ConfirmPackagingCreditControllerSpec.scala
- test/views/returns/credits/ConfirmPackagingCreditViewSpec.scala
> Credits v2 confirmation page

- app/config/FrontendAppConfig.scala
- app/controllers/returns/credits/WhatDoYouWantToDoController.scala
- app/views/returns/credits/WhatDoYouWantToDoView.scala.html
- conf/app.routes
- conf/application.conf
- conf/messages.cy
- conf/messages.en
- test/views/returns/WhatDoYouWantToDoViewSpec.scala
> Credits what to do view

- app/viewmodels/checkAnswers/returns/ImportedPlasticPackagingWeightSummary.scala
- app/viewmodels/checkAnswers/returns/ManufacturedPlasticPackagingWeightSummary.scala
> Adding hidden text on Total plastic packaging summary page

- app/controllers/amends/ViewReturnSummaryController.scala
- app/controllers/returns/StartYourReturnController.scala
- app/models/UserAnswers.scala
- app/navigation/ReturnsJourneyNavigator.scala
- conf/application.conf
- test/controllers/returns/StartYourReturnControllerSpec.scala
- test/navigation/FakeNavigator.scala
- test/navigation/NavigatorSpec.scala
- test/navigation/ReturnsJourneyNavigatorSpec.scala
> Users first return

- app/views/returns/credits/ConvertedCreditsView.scala.html
- app/views/returns/credits/ExportedCreditsView.scala.html
> Move error box to top of exported-credit and converted-credit pages

- a11y/views/returns/ReturnsCheckYourAnswerViewA11ySpec.scala
- app/config/FrontendAppConfig.scala
- app/controllers/returns/ReturnsCheckYourAnswersController.scala
- app/models/returns/Credits.scala
- app/models/returns/CreditsClaimedDetails.scala
- app/models/returns/NoCreditsClaimed.scala
- app/views/components/returns/checkYourAnswer/CreditsSection.scala.html
- app/views/components/returns/checkYourAnswer/credits/CreditsClaimed.scala.html
- app/views/components/returns/checkYourAnswer/credits/NoCreditsClaimed.scala.html
- app/views/returns/ReturnsCheckYourAnswersView.scala.html
- conf/messages.cy
- conf/messages.en
- test/base/ViewSpecBase.scala
- test/controllers/returns/ReturnsCheckYourAnswersControllerSpec.scala
- test/models/returns/ClaimedCreditsDetailsSpec.scala
- test/views/returns/ReturnsCheckYourAnswersViewSpec.scala
- test/views/returns/credits/ConvertedCreditsViewSpec.scala
- test/views/returns/credits/ExportedCreditsViewSpec.scala
> Credits cya

- a11y/views/ConfirmPlasticCreditViewA11ySpec.scala
- app/controllers/returns/credits/ConfirmPackagingCreditController.scala
- app/views/returns/credits/ConfirmPackagingCreditView.scala.html
- test/controllers/returns/credits/ConfirmPackagingCreditControllerSpec.scala
- test/views/returns/credits/ConfirmPackagingCreditViewSpec.scala
> Correct checkmode credits returns

- a11y/views/returns/ReturnsCheckYourAnswerViewA11ySpec.scala
- app/controllers/returns/ReturnsCheckYourAnswersController.scala
- app/views/components/returns/checkYourAnswer/CreditsSection.scala.html
- app/views/components/returns/checkYourAnswer/credits/NoCreditsAvailable.scala.html
- app/views/returns/ReturnsCheckYourAnswersView.scala.html
- conf/messages.cy
- conf/messages.en
- test/connectors/DirectDebitConnectorSpec.scala
- test/controllers/actions/DataRetrievalActionSpec.scala
- test/controllers/amends/CancelAmendControllerSpec.scala
- test/controllers/amends/CheckYourAnswersControllerSpec.scala
- test/controllers/returns/ReturnsCheckYourAnswersControllerSpec.scala
- test/controllers/returns/StartYourReturnControllerSpec.scala
- test/views/amends/AmendConfirmationViewSpec.scala
- test/views/returns/ReturnsCheckYourAnswersViewSpec.scala
> Pptp 2514 cya first returns

- a11y/views/returns/TooMuchCreditClaimedViewA11ySpec.scala
- app/controllers/returns/NowStartYourReturnController.scala
- app/views/amends/CheckYourAnswersView.scala.html
- app/views/components/heading.scala.html
- app/views/returns/ConfirmPlasticPackagingTotalView.scala.html
- app/views/returns/NotStartOtherReturnsView.scala.html
- app/views/returns/NowStartYourReturnView.scala.html
- app/views/returns/ReturnsCheckYourAnswersView.scala.html
- app/views/returns/SubmittedReturnsView.scala.html
- app/views/returns/credits/ConfirmPackagingCreditView.scala.html
- test/views/returns/ConfirmPlasticPackagingTotalViewSpec.scala
> added a11y test and h1 resizing

- app/views/components/conditionalYesNoRadio.scala.html
- app/views/returns/credits/WhatDoYouWantToDoView.scala.html
Enables link in eorror message to first radio
> Change ID's to match fieldname

- app/views/returns/credits/ConfirmPackagingCreditView.scala.html
> remove stray brakcet

- a11y/views/CreateReturnA11ySpec.scala
- app/controllers/returns/ReturnConfirmationController.scala
- app/controllers/returns/ReturnsCheckYourAnswersController.scala
- app/views/components/SectionH2Heading.scala.html
- app/views/components/returns/checkYourAnswer/CreditsSection.scala.html
- app/views/returns/ReturnConfirmationView.scala.html
- app/views/returns/ReturnsCheckYourAnswersView.scala.html
- conf/app.routes
- conf/messages.cy
- conf/messages.en
- test/controllers/returns/ReturnConfirmationControllerSpec.scala
- test/controllers/returns/ReturnsCheckYourAnswersControllerSpec.scala
- test/views/returns/ReturnConfirmationViewSpec.scala
- test/views/returns/credits/ConvertedCreditsViewSpec.scala
- test/views/returns/credits/ExportedCreditsViewSpec.scala
Adjust heading sizes, in CYA. Weight must be between 1kg and 99,999,999,999kg. Add some advice on where to see your credit to the return submitted page
> More credit tweaks

- app/controllers/IndexController.scala
- app/views/IndexView.scala.html
- conf/messages.cy
- conf/messages.en
- test/controllers/IndexControllerSpec.scala
- test/views/IndexViewSpec.scala
Needs content however, homepage would now know if users first return for conditional link
> Check for fulfilled obligations on homepage

- conf/messages.cy
-confirm credits page
-submit return button welsh text
> Welsh patch confirm credits

- app/views/components/Strong.scala.html
- app/views/returns/ReturnsCheckYourAnswersView.scala.html
- conf/messages.cy
- conf/messages.en
> Move calculation foot note and add one for credit

- conf/app.routes
Hot fix for now, will look at a way to make this work with reverse routing so this doesnt happen again
> BTA entry point redirect

- app/controllers/actions/AuthFunction.scala
- app/controllers/actions/CommonAuth.scala
- app/controllers/actions/IdentifierAction.scala
- test/controllers/actions/AuthAgentActionSpec.scala
- test/controllers/actions/AuthCheckActionSpec.scala
- test/support/FakeRequest.scala
If approved will clean up configs
> original target is passed on to auth for continue

- project/AppDependencies.scala
> [PPTP-2608, PPTP-2610]: upgrade banner to fix accessibility issues

- app/connectors/TaxReturnsConnector.scala
- test/connectors/TaxReturnsConnectorSpec.scala
> Turn TaxReturnsConnectorSpec into unit tests

- conf/messages.en
- test/views/returns/ImportedPlasticPackagingWeightViewSpec.scala
- test/views/returns/ManufacturedPlasticPackagingWeightViewSpec.scala
> PPTP-2607: manufacture and imported weight content changes

- app/views/components/SectionH3Heading.scala.html
- app/views/returns/ReturnsCheckYourAnswersView.scala.html
- conf/application.conf
- conf/messages.cy
- conf/messages.en
- test/connectors/TaxReturnsConnectorSpec.scala
- test/views/returns/ReturnsCheckYourAnswersViewSpec.scala
Update only the Returns CYA content as per SoT (https://docs.google.com/spreadsheets/d/1u1POl1uW_XXlQ9KuTMQW_UPC_quxpd7La4vyNMph3GA/edit#gid=665018566)
> Update returns CYA content as per SoT

- test-utils/generators/Generators.scala
> Non white space strings

- a11y/views/returns/AlreadySubmittedViewA11ySpec.scala
- app/controllers/returns/AlreadySubmittedController.scala
- app/controllers/returns/ReturnsCheckYourAnswersController.scala
- app/repositories/SessionRepository.scala
- app/views/returns/AlreadySubmittedView.scala.html
- conf/app.routes
- conf/messages.cy
- conf/messages.en
- test/controllers/returns/AlreadySubmittedControllerSpec.scala
- test/views/returns/AlreadySubmittedViewSpec.scala
> content changes

- app/views/DeregisteredView.scala.html
- remove back link from /deregistered
- change font size to l on /deregistered
> Desiign and content review comments

- README.md
- a11y/views/amends/CancelAmendViewA11ySpec.scala
- app/controllers/amends/CancelAmendController.scala
- app/views/ErrorTemplate.scala.html
- app/views/amends/CancelAmendView.scala.html
- build.sbt
- conf/messages.cy
- conf/messages.en
- test/controllers/amends/CancelAmendControllerSpec.scala
- test/views/amends/CancelAmendViewSpec.scala
If someone back-buttons to the cancel-amend page we get an unnecessary exception and alert
> No 5xx on cancel-amend via back button

- app/controllers/amends/ViewReturnSummaryController.scala
- test/controllers/ViewReturnSummaryControllerSpec.scala
> PPTP-2671 changed the view return summary from exceptions to not found

- app/controllers/amends/ViewReturnSummaryController.scala
- app/controllers/helpers/TaxReturnHelper.scala
- test/controllers/ViewReturnSummaryControllerSpec.scala
> Pptp 2674 More Not Found for bad period keys

- a11y/views/changeGroupLead/ChooseNewGroupLeadA11ySpec.scala
- app/config/FrontendAppConfig.scala
- app/views/changeGroupLead/ChooseNewGroupLeadView.scala.html
- conf/application.conf
- conf/messages.cy
- conf/messages.en
- test/controllers/changeGroupLead/ChooseNewGroupLeadControllerSpec.scala
- test/views/changeGroupLead/ChooseNewGroupLeadViewSpec.scala
> Add new group member link and accessibility tests

- a11y/views/changeGroupLead/ChooseNewGroupLeadA11ySpec.scala
- app/controllers/changeGroupLead/ChooseNewGroupLeadController.scala
- app/views/changeGroupLead/ChooseNewGroupLeadView.scala.html
- test/controllers/changeGroupLead/ChooseNewGroupLeadControllerSpec.scala
- test/views/changeGroupLead/ChooseNewGroupLeadViewSpec.scala
> Updating usage of GroupMembers model

- a11y/views/changeGroupLead/ChooseNewGroupLeadA11ySpec.scala
- a11y/views/changeGrouplead/NewGroupLeadCheckYourAnswerViewA11ySpec.scala
- app/config/FrontendAppConfig.scala
- app/controllers/changeGroupLead/ChooseNewGroupLeadController.scala
- app/controllers/changeGroupLead/FeatureGuard.scala
- app/controllers/changeGroupLead/NewGroupLeadCheckYourAnswerController.scala
- app/controllers/changeGroupLead/NewGroupLeadConfirmationController.scala
- app/forms/changeGroupLead/SelectNewGroupLeadForm.scala
- app/models/changeGroupLead/RepresentativeMemberDetails.scala
- app/views/changeGroupLead/NewGroupLeadCheckYourAnswerView.scala.html
- app/views/changeGroupLead/NewGroupLeadConfirmationView.scala.html
- conf/app.routes
- conf/messages.cy
- conf/messages.en
- test/controllers/changeGroupLead/ChooseNewGroupLeadControllerSpec.scala
- test/controllers/changeGroupLead/NewGroupLeadCheckYourAnswerControllerSpec.scala
- test/controllers/package.scala
- test/views/changeGroupLead/ChooseNewGroupLeadViewSpec.scala
- test/views/changeGroupLead/NewGroupLeadCheckYourAnswerViewSpec.scala
- test/views/changeGroupLead/NewGroupLeadConfirmationViewSpec.scala
> New group lead cya

- a11y/views/changeGroupLead/NewGroupLeadConfirmationA11ySpec.scala
- app/views/changeGroupLead/NewGroupLeadConfirmationView.scala.html
- conf/app.routes
- conf/messages.cy
- conf/messages.en
- test/views/changeGroupLead/NewGroupLeadConfirmationViewSpec.scala
> Change Group Rep: Request Submitted - Adding page updates and specs

- app/controllers/changeGroupLead/ChooseNewGroupLeadController.scala
- app/controllers/changeGroupLead/MainContactNameController.scala
- app/forms/changeGroupLead/MainContactNameFormProvider.scala
- app/navigation/ChangeGroupLeadNavigator.scala
- app/pages/changeGroupLead/MainContactNamePage.scala
- app/viewmodels/checkAnswers/changeGroupLead/MainContactNameSummary.scala
- app/views/changeGroupLead/MainContactNameView.scala.html
- conf/app.routes
- conf/messages.en
- test-utils/generators/PageGenerators.scala
- test-utils/generators/UserAnswersEntryGenerators.scala
- test-utils/generators/UserAnswersGenerator.scala
- test/controllers/changeGroupLead/MainContactNameControllerSpec.scala
- test/forms/changeGroupLead/MainContactNameFormProviderSpec.scala
- test/navigation/ChangeGroupLeadNavigatorSpec.scala
- test/pages/changeGroupLead/MainContactNamePageSpec.scala
- test/views/changeGroupLead/MainContactNameViewSpec.scala
todo: 
Content
Form validation/ error messages
> Main Contact Name pages

- app/forms/changeGroupLead/SelectNewGroupLeadForm.scala
- app/views/changeGroupLead/ChooseNewGroupLeadView.scala.html
- conf/app.routes
- conf/messages.cy
- conf/messages.en
- project/plugins.sbt
- test/forms/changeGroupLead/SelectNewGroupLeadFromSpec.scala
- test/views/changeGroupLead/ChooseNewGroupLeadViewSpec.scala
> Updating content and url - Select new group representative page

- app/controllers/changeGroupLead/MainContactNameController.scala
- app/forms/changeGroupLead/MainContactNameFormProvider.scala
- app/forms/changeGroupLead/SelectNewGroupLeadForm.scala
- app/navigation/ChangeGroupLeadNavigator.scala
- app/views/changeGroupLead/MainContactNameView.scala.html
- conf/app.routes
- conf/messages.en
- test/controllers/changeGroupLead/MainContactNameControllerSpec.scala
- test/forms/changeGroupLead/MainContactNameFormProviderSpec.scala
- test/views/changeGroupLead/MainContactNameViewSpec.scala
> Contact person name

- conf/messages.en
- test/views/changeGroupLead/MainContactJobTitleViewSpec.scala
> refactor job title view spec and typo in messages

- app/models/subscription/AddressDetails.scala
- app/models/subscription/GroupMembers.scala
- app/models/subscription/group/GroupPartnershipDetails.scala
- test/models/subscription/GroupMembersSpec.scala
- test/services/SubscriptionServiceSpec.scala
> filter group members from rep and nonGb

- test/controllers/changeGroupLead/NewGroupLeadCheckYourAnswerControllerSpec.scala
> Tweak a unit test to be more specific

- app/views/changeGroupLead/MainContactNameView.scala.html
- conf/messages.en
- test/views/changeGroupLead/MainContactNameViewSpec.scala
> Updating contact name title content

- app/controllers/changeGroupLead/NewGroupLeadCheckYourAnswerController.scala
- app/models/changeGroupLead/NewGroupLeadAddressDetails.scala
- app/services/CountryService.scala
- app/viewmodels/checkAnswers/changeGroupLead/NewGroupLeadEnterContactAddressSummary.scala
- app/views/changeGroupLead/NewGroupLeadEnterContactAddressView.scala.html
- test/controllers/changeGroupLead/NewGroupLeadCheckYourAnswerControllerSpec.scala
- test/views/changeGroupLead/NewGroupLeadCheckYourAnswerViewSpec.scala
> showing country name instead of code

- a11y/views/changeGroupLead/MainContactJobTitleA11ySpec.scala
- a11y/views/changeGroupLead/MainContactNameA11ySpec.scala
- app/views/changeGroupLead/MainContactNameView.scala.html
> Adding id to headingLabel for contact name, and adding a11y specs

- app/connectors/TaxReturnsConnector.scala
- test/connectors/TaxReturnsConnectorSpec.scala
> Pptp 2558 change to proper rest operation

- conf/messages.cy
> added welsh

- conf/messages.cy
> Adding welsh non-Uk postcode validation

- app/navigation/ReturnsJourneyNavigator.scala
- test/navigation/NavigatorSpec.scala
> adding extra scenario

- a11y/views/returns/ReturnsCheckYourAnswerViewA11ySpec.scala
- app/controllers/helpers/TaxReturnViewModel.scala
- app/navigation/ReturnsJourneyNavigator.scala
- app/views/returns/ReturnsCheckYourAnswersView.scala.html
- conf/messages.cy
- conf/messages.en
- test/controllers/helpers/TaxReturnViewModelSpec.scala
- test/navigation/NavigatorSpec.scala
- test/views/returns/ReturnsCheckYourAnswersViewSpec.scala
> 3rd part hens cya

- app/controllers/IndexController.scala
Reverts hmrc/plastic-packaging-tax-returns-frontend#446
> Revert "test log"

- .g8/longPage/app/controllers/$className$Controller.scala
- .g8/longPage/app/forms/$className$FormProvider.scala
- .g8/longPage/app/viewmodels/checkAnswers/$className$Summary.scala
- .g8/longPage/generated-test/controllers/$className$ControllerSpec.scala
- .g8/longPage/generated-test/forms/$className$FormProviderSpec.scala
> fixed most of the error generate for the longPage

- app/controllers/helpers/NonExportedAmountHelper.scala
- app/controllers/returns/AnotherBusinessExportWeightController.scala
- app/controllers/returns/ConfirmPlasticPackagingTotalController.scala
- app/controllers/returns/DirectlyExportedComponentsController.scala
- app/controllers/returns/ExportedPlasticPackagingWeightController.scala
- app/controllers/returns/NonExportedHumanMedicinesPlasticPackagingController.scala
- app/controllers/returns/NonExportedHumanMedicinesPlasticPackagingWeightController.scala
- app/controllers/returns/NonExportedRecycledPlasticPackagingController.scala
- app/controllers/returns/NonExportedRecycledPlasticPackagingWeightController.scala
- app/controllers/returns/PlasticExportedByAnotherBusinessController.scala
- app/navigation/ReturnsJourneyNavigator.scala
- app/services/ExportedPlasticAnswer.scala
- app/viewmodels/checkAnswers/returns/PlasticPackagingTotalSummary.scala
- test/controllers/AnotherBusinessExportWeightControllerSpec.scala
- test/controllers/helpers/NonExportedAmountHelperSpec.scala
- test/controllers/returns/ConfirmPlasticPackagingTotalControllerSpec.scala
- test/controllers/returns/DirectlyExportedComponentsControllerSpec.scala
- test/controllers/returns/ExportedPlasticPackagingWeightControllerSpec.scala
- test/controllers/returns/NonExportedHumanMedicinesPlasticPackagingControllerSpec.scala
- test/controllers/returns/NonExportedHumanMedicinesPlasticPackagingWeightControllerSpec.scala
- test/controllers/returns/NonExportedRecycledPlasticPackagingControllerSpec.scala
- test/controllers/returns/NonExportedRecycledPlasticPackagingWeightControllerSpec.scala
- test/controllers/returns/PlasticExportedByAnotherBusinessControllerSpec.scala
- test/navigation/FakeNavigator.scala
- test/navigation/NavigatorSpec.scala
- test/navigation/ReturnsJourneyNavigatorSpec.scala
- test/services/ExportedPlasticAnswerSpec.scala
> changed NonExportedAmountHelper object into a class

- app/controllers/returns/AnotherBusinessExportWeightController.scala
- app/controllers/returns/ExportedPlasticPackagingWeightController.scala
- test/controllers/returns/AnotherBusinessExportWeightControllerSpec.scala
- test/controllers/returns/ExportedPlasticPackagingWeightControllerSpec.scala
> 3rd part hens cya fixes

- conf/messages.cy
- conf/messages.en
- test/views/returns/credits/ConvertedCreditsViewSpec.scala
- test/views/returns/credits/ExportedCreditsViewSpec.scala
> Updating range error content

- a11y/views/changeGroupLead/ChooseNewGroupLeadA11ySpec.scala
- app/controllers/changeGroupLead/ChooseNewGroupLeadController.scala
- app/controllers/changeGroupLead/MainContactNameController.scala
- app/controllers/changeGroupLead/NewGroupLeadEnterContactAddressController.scala
- app/forms/changeGroupLead/SelectNewGroupLeadForm.scala
- app/models/subscription/GroupMembers.scala
- app/pages/changeGroupLead/ChooseNewGroupLeadPage.scala
- app/viewmodels/checkAnswers/changeGroupLead/ChooseNewGroupLeadSummary.scala
- app/views/changeGroupLead/ChooseNewGroupLeadView.scala.html
- test/controllers/changeGroupLead/ChooseNewGroupLeadControllerSpec.scala
- test/controllers/changeGroupLead/MainContactNameControllerSpec.scala
- test/controllers/changeGroupLead/NewGroupLeadCheckYourAnswerControllerSpec.scala
- test/controllers/changeGroupLead/NewGroupLeadEnterContactAddressControllerSpec.scala
- test/forms/changeGroupLead/SelectNewGroupLeadFormSpec.scala
- test/models/subscription/GroupMembersSpec.scala
- test/services/SubscriptionServiceSpec.scala
- test/views/changeGroupLead/ChooseNewGroupLeadViewSpec.scala
> Pptp 2756 CGL Member now stores the CRN

- app/controllers/helpers/NonExportedAmountHelper.scala
- app/controllers/returns/NonExportedHumanMedicinesPlasticPackagingWeightController.scala
- test/controllers/helpers/NonExportedAmountHelperSpec.scala
- test/controllers/returns/NonExportedHumanMedicinesPlasticPackagingWeightControllerSpec.scala
Quick fix for people possibly getting sent back to the account page after we deploy
> Yet another deployment issue

- app/connectors/DownstreamServiceError.scala
- app/handlers/ErrorHandler.scala
- test/controllers/returns/ReturnsCheckYourAnswersControllerSpec.scala
> Custom error handler

- app/handlers/ErrorHandler.scala
> And upstream

- a11y/views/AmendReturnA11ySpec.scala
- a11y/views/amends/CheckYourAnswerA11ySpec.scala
- a11y/views/returns/ReturnsCheckYourAnswerViewA11ySpec.scala
- app/connectors/TaxReturnsConnector.scala
- app/controllers/amends/ViewReturnSummaryController.scala
- app/controllers/helpers/TaxReturnHelper.scala
- app/models/returns/Calculations.scala
- app/models/returns/ReturnDisplayApi.scala
- app/viewmodels/TaxReturnViewModel.scala
- app/viewmodels/checkAnswers/ViewReturnSummaryViewModel.scala
- app/viewmodels/package.scala
- app/views/amends/ViewReturnSummaryView.scala.html
- app/views/returns/ReturnsCheckYourAnswersView.scala.html
- conf/messages.cy
- conf/messages.en
- test/controllers/ViewReturnSummaryControllerSpec.scala
- test/controllers/amends/CheckYourAnswersControllerSpec.scala
- test/controllers/helpers/TaxReturnViewModelSpec.scala
- test/controllers/returns/ReturnsCheckYourAnswersControllerSpec.scala
- test/viewmodels/ViewmodelsSpec.scala
- test/views/amends/CheckYourAnswersViewSpec.scala
- test/views/amends/ViewReturnSummaryViewSpec.scala
- test/views/returns/ReturnsCheckYourAnswersViewSpec.scala
> retrieve tax rate from the back-end

- app/controllers/actions/AuthAction.scala
- test/controllers/actions/AuthenticatedIdentifierActionSpec.scala
> switching order of authorised user order for stubs

- app/assets/stylesheets/application.scss
- app/views/templates/Layout.scala.html
> PPTP-2820 | hide back links when js is disabled

- app/views/changeGroupLead/NewGroupLeadEnterContactAddressView.scala.html
- test/views/changeGroupLead/NewGroupLeadEnterContactAddressViewSpec.scala
Fix for a11y issue https://jira.tools.tax.service.gov.uk/browse/PPTP-2819
> PPTP-2819 - Adding autocomplete attributes for NewGroupLeadEnterContactAddressView

- app/views/changeGroupLead/ChooseNewGroupLeadView.scala.html
- app/views/components/AmendsCyaTable.scala.html
- app/views/returns/ReturnsCheckYourAnswersView.scala.html
- app/views/returns/credits/WhatDoYouWantToDoView.scala.html
- app/views/templates/HiddenContent.scala.html
- app/views/templates/YesNoLayout.scala.html
- test/views/templates/YesNoLayoutSpec.scala
> added legend to radio buttons

- app/controllers/amends/CheckYourAnswersController.scala
- app/viewmodels/checkAnswers/amends/AmendTotalDeductionSummary.scala
- app/viewmodels/checkAnswers/amends/AmendTotalPlasticPackagingSummary.scala
- test/viewmodels/checkYourAnswer/amends/AmendTotalDeductionSummarySpec.scala
- test/viewmodels/checkYourAnswer/amends/AmendTotalPlasticPackagingSummarySpec.scala
> PPTP-2538: amended details should be empty

- a11y/views/amends/SubmittedReturnsViewA11ySpec.scala
- app/views/IndexView.scala.html
- app/views/amends/CheckYourAnswersView.scala.html
- app/views/components/AmendsCyaTable.scala.html
- app/views/components/TaxReturnLink.scala.html
- app/views/returns/AlreadySubmittedView.scala.html
- app/views/returns/SubmittedReturnsView.scala.html
- test/views/IndexViewSpec.scala
> PPTP-2827: invalid <br> tag. Replaced <br> with margin

- app/views/components/conditionalYesNoRadio.scala.html
- app/views/returns/credits/ConvertedCreditsView.scala.html
- app/views/returns/credits/ExportedCreditsView.scala.html
- test/views/returns/credits/ConvertedCreditsViewSpec.scala
- test/views/returns/credits/ExportedCreditsViewSpec.scala
Note - accessibility linter (views) and accessibility assessment (acceptance) tests ran successfully
> PPTP-2818 - Adding fieldset legend to credits input views

- app/views/returns/credits/ConfirmPackagingCreditView.scala.html
- test/views/returns/credits/ConfirmPackagingCreditViewSpec.scala
> PPTP-2824 - Updating position of change credit link

- app/views/returns/SubmittedReturnsView.scala.html
- test/views/returns/SubmittedReturnsViewSpec.scala
> removed indentation when no returns are available

- tampermonkey/PPT_Returns_AutoComplete.js
- Creating TamperMonkey script for Returns journey
- Adding quickSubmit panel and options for additional journeys
TODO: Extend support for "Return with credit", "Amend Return", "Deregister", "Change group lead" journeys
> Fixing TamperMonkey for Returns service

- app/controllers/returns/credits/ConvertedCreditsWeightController.scala
- app/forms/returns/credits/ConvertedCreditsWeightFormProvider.scala
- app/models/UserAnswers.scala
- app/views/returns/credits/ConvertedCreditsWeightView.scala.html
- conf/messages.en
- test/base/utils/JourneyActionAnswer.scala
- test/controllers/returns/credits/ConvertedCreditsWeightControllerSpec.scala
- test/forms/returns/credits/ConvertedCreditsWeightFormProviderSpec.scala
- test/views/returns/credits/ConvertedCreditsWeightViewSpec.scala
> Partridge converted weight

- app/controllers/returns/ReturnsCheckYourAnswersController.scala
- app/controllers/returns/credits/ClaimedCredits.scala
- app/models/returns/CreditsClaimedDetails.scala
- app/navigation/ReturnsJourneyNavigator.scala
- app/pages/returns/credits/ConvertedCreditsPage.scala
- app/pages/returns/credits/ExportedCreditsPage.scala
- test/controllers/returns/ReturnsCheckYourAnswersControllerSpec.scala
- test/models/returns/ClaimedCreditsDetailsSpec.scala
- test/navigation/ReturnsJourneyNavigatorSpec.scala
Nav and CYA changes for single year claim
> Partridge calculations

- app/controllers/returns/credits/ClaimForWhichYearController.scala
- test/controllers/returns/credits/ClaimForWhichYearControllerSpec.scala
Redirect to summary page if there are no options. This still potentially leaves one radio option but this is still useable unlike 0 options
> Filter Credit date range options based on already answered

- app/controllers/returns/credits/ConfirmPackagingCreditController.scala
- app/controllers/returns/credits/ExportedCreditsController.scala
- app/controllers/returns/credits/ExportedCreditsWeightController.scala
- app/navigation/ReturnsJourneyNavigator.scala
- app/viewmodels/checkAnswers/returns/credits/CreditsConvertedWeightSummary.scala
- app/viewmodels/checkAnswers/returns/credits/CreditsExportedWeightSummary.scala
- test/controllers/returns/credits/ConfirmPackagingCreditControllerSpec.scala
- test/controllers/returns/credits/ExportedCreditsControllerSpec.scala
- test/controllers/returns/credits/ExportedCreditsWeightControllerSpec.scala
- test/navigation/ReturnsJourneyNavigatorSpec.scala
> Fix possible infinite loop with incomplete user answers
