- app/project/build.properties
- app/uk/gov/hmrc/plasticpackagingtax/returns/controllers/home/HomeController.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/controllers/returns/StartController.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/views/home/home_page.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/returns/views/partials/siteHeader.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/start_page.scala.html
- conf/app.routes
- conf/home.routes
- conf/returns.routes
- test/uk/gov/hmrc/plasticpackagingtax/returns/controllers/home/HomeControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/controllers/returns/StartControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/StartPageViewSpec.scala
Routes/Packages can soon become messy and this is a better approach.
Obviously the problem here is that Play actually has an opinion/bug on how the routes and controllers are linked and it is better to provide a clear division on routes and controllers underpinned by the same name.
https://github.com/playframework/playframework/issues/6719
> PPTP-445 Rename packages and tidy app.Routes file

- app/assets/stylesheets/_cards.scss
The default CSS classes need to be defined at the top of the file, not at the bottom.
> BAU - Fix Cards CSS on the Account homepage

- app/assets/stylesheets/_returns.scss
- app/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/check_your_return_page.scala.html
Some rows require some border lines in order to provide emphasis on the
values of those same rows
In the past we have used the CSS id `#row-border`, this is a problem
because CSS ids have to be unique per page.
This change will transform the `row-order` into a CSS class.
> PPTP-838 Replace CSS #id .class to style rows

- app/uk/gov/hmrc/plasticpackagingtax/returns/views/components/link.scala.html
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/home/UnauthorisedViewSpec.scala
- remove target attribute from links where not needed
- add rel="noopener noreferrer" where target is "_blank" (open in new tab)
> PPTP-1118 - Links vulnerable to reverse tabnabbing

- app/uk/gov/hmrc/plasticpackagingtax/returns/views/components/govukFlexibleLayout.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/returns/views/main_template.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/check_your_return_page.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/converted_packaging_credit_page.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/exported_plastic_weight_page.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/human_medicines_plastic_weight_page.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/imported_plastic_weight_page.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/manufactured_plastic_weight_page.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/recycled_plastic_weight_page.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/returns/views/subscriptions/primary_contact_name_page.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/returns/views/subscriptions/view_subscription_page.scala.html
- build.sbt
- conf/application.conf
- project/AppDependencies.scala
- project/plugins.sbt
- test/uk/gov/hmrc/plasticpackagingtax/returns/audit/AuditorSpec.scala
Update versions in AppDependencies.scala and plugins.sbt
- removed play-frontend-govuk lib (pulled in by play-frontend-hmrc)
Code changes due to
- removal of static helpers in play-frontend-govuk
- change in auditing message structure
Fixed following build warnings
```
2021-09-23 07:57:14,694 level=[WARN] logger=[uk.gov.hmrc.play.bootstrap.frontend.filters.FrontendFilters] thread=[pool-1-thread-1] rid user=[] message=[play.http.filters = "uk.gov.hmrc.play.bootstrap.frontend.filters.FrontendFilter" is no longer required and can be removed. Filters are configured using play's default filter system: https://www.playframework.com/documentation/2.7.x/Filters#Default-Filters] 
2021-09-23 07:57:14,693 level=[WARN] logger=[play.filters.headers.SecurityHeadersConfig] thread=[pool-1-thread-1] rid …
```
> PPTP-1210 - Update application library dependencies

- app/uk/gov/hmrc/plasticpackagingtax/returns/config/ErrorHandler.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/controllers/actions/AuthAction.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/base/MockAuthAction.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/config/ErrorHandlerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/controllers/actions/AuthActionSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/controllers/subscriptions/ViewSubscriptionControllerSpec.scala
Change the way we handle "authorisation" errors to stop them getting logged as exceptions
> BAU - auth error handling moved to AuthAction

- app/uk/gov/hmrc/plasticpackagingtax/returns/config/AppConfig.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/controllers/returns/ReturnsInformationController.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/views/components/bulletList.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/returns/views/components/bulletListNavigation.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/returns/views/components/pageTitle.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/returns/views/components/paragraph.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/confirmation_page.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/returns_information_page.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/start_page.scala.html
- conf/application.conf
- conf/messages.en
- conf/returns.routes
- test/uk/gov/hmrc/plasticpackagingtax/returns/controllers/returns/ReturnsInformationControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/home/SessionTimedOutViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/ConvertedPackagingCreditViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/ExportedPlasticWeightViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/HumanMedicinesPlasticWeightViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/ImportedPlasticWeightViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/ManufacturedPlasticWeightViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/RecycledPlasticWeightViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/ReturnsInformationPageViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/subscriptions/PrimaryContactNameViewSpec.scala
A new bulletList component was created for the bullet list on this new page. The original bulletList component was renamed to bulletListNavigation since it was rendering a nav element which used a contained bullet list. The start_page and confirmation_page views were updated to use the new bulletList component since these were not navigational bullet lists.
The pageTitle component was updated to use the "govuk-heading-l" class as per the prototype.
A new paragraph component was added which accepts html content rather than just a String so that links could be wrapped in <p> tags.
> PPTP-1066 : Returns preparation info page

- test/uk/gov/hmrc/plasticpackagingtax/returns/base/unit/UnitViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/components/LinkPartialViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/home/HomePageViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/home/SessionTimedOutViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/home/UnauthorisedViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/home/ViewSubscriptionViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/model/SignOutReasonSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/model/TitleSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/CheckYourReturnViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/ConfirmationViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/ConvertedPackagingCreditViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/ExportedPlasticWeightViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/HumanMedicinesPlasticWeightViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/ImportedPlasticWeightViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/ManufacturedPlasticWeightViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/RecycledPlasticWeightViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/ReturnsInformationPageViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/StartPageViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/subscriptions/PrimaryContactNameViewSpec.scala
Made UnitViewSpec abstract to encourage ViewSpecs to exercise generated render methods
> BAU - increase view spec code coverage by exercising generated methods

- app/uk/gov/hmrc/plasticpackagingtax/returns/config/AppConfig.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/views/home/home_page.scala.html
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/home/HomePageViewSpec.scala
This now resides in the registration service.
Reg FE: https://github.com/hmrc/plastic-packaging-tax-registration-frontend/pull/286
> PPTP-1540 : Update Link to Registration Amendment Page

- app/uk/gov/hmrc/plasticpackagingtax/returns/audit/CreateTaxReturnEvent.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/models/domain/TaxReturn.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/models/obligations/Obligation.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/models/request/JourneyAction.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/views/components/returnsSectionHeading.scala.html
- build.sbt
- conf/messages.en
- test/uk/gov/hmrc/plasticpackagingtax/returns/base/unit/MockJourneyAction.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/builders/TaxReturnBuilder.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/connectors/TaxReturnsConnectorSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/models/dmoain/TaxReturnSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/models/request/JourneyActionSpec.scala
We've added details of a return's obligation details to the main TaxReturn class.
BE PR: https://github.com/hmrc/plastic-packaging-tax-returns/pull/53
> BAU : Returns Foundation

- app/uk/gov/hmrc/plasticpackagingtax/returns/audit/CreateTaxReturnEvent.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/models/domain/TaxReturn.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/models/request/JourneyAction.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/builders/TaxReturnBuilder.scala
This is necessary since successful registration results in the creation of a TaxReturn. Thus, we need to remain compatible with these existing TaxReturns which exist in the production Returns Mongo.
> BAU : Ensure TaxReturn changes are backwards-compat

- project/AppDependencies.scala
Upgrading the `play-frontend-hmrc` library following guidance in the [accessibility test report](https://build.tax.service.gov.uk/job/Plastic%20Packaging%20Tax/job/plastic-packaging-tax-a11y-tests/40/Accessibility_20Check_20Report/) to resolve issues identified by VNU.
> Upgrade library to resolve accessibility issues

- app/uk/gov/hmrc/plasticpackagingtax/returns/config/AppConfig.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/connectors/TaxReturnsConnectorSpec.scala
Probably restores returns based pages.
Frontend url change was applied to a back end end point path.
> Correct path for returns backend end points

- app/uk/gov/hmrc/plasticpackagingtax/returns/controllers/actions/AuthAction.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/base/MockAuthAction.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/controllers/actions/AuthActionSpec.scala
Agents who have been delegated access can access PPT returns.
- AuthAction uses the authorisation Enrolment predicate to explicitly request the PPT enrol from auth.
- The `auth` service will only evaluate an agent delegation for an Enrolment if it is explicitly mentioned in the authorisation predicate (See [auth AgentDelegationPredicate](/hmrc/auth/blob/main/app/auth/authorise/predicate/AgentDelegationPredicate.scala))
The enrolments currently fetched using retrieve allEnrolments have non be evaluated for agent access.
- The Enrolment predicate is marked with the `ppt-auth` delegated auth rule.
We believe that `auth` passes this parameter to `agent-access-control` which looks for an agent delegation.
The existing behaviour of redirecting non enrolled users to registration front end is …
> PPTP-1762 - Agents with delegated access can access Plastics Returns

- conf/application.conf
(and possibly in the real environments as well)
Looks like services cannot assign themselves root paths on the platform.
This fixes local sign in journey redirect url.
> Returns loginContinue urls needs to be prefixed to work locally

- app/uk/gov/hmrc/plasticpackagingtax/returns/controllers/actions/AuthAction.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/base/MockAuthAction.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/controllers/actions/AuthActionSpec.scala
As per #111 but without considerign agents, our auth call should document the need for a PPT enrolment using the auth Enrolment predicate.
This becomes important is this service needs to be enabled for agents in the future.
Doing this now has no user facing effect; re directions to registration for missing enrolments continue to work as normal.
> Use auth enrolment predicate

- app/uk/gov/hmrc/plasticpackagingtax/returns/connectors/TaxReturnsConnector.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/connectors/TaxReturnsConnectorSpec.scala
To match the same back end API change.
This is a step towards been able to support agent auth in the backend. 
Paired with https://github.com/hmrc/plastic-packaging-tax-returns/pull/62
> Create return call specifies the ppt references on the path

- app/uk/gov/hmrc/plasticpackagingtax/returns/config/AppConfig.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/controllers/LanguageController.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/views/main_template.scala.html
- conf/app.routes
- conf/application.conf
- conf/messages.cy
- test/uk/gov/hmrc/plasticpackagingtax/returns/controllers/LanguageControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/StartPageViewSpec.scala
- page language switching added
- feature has as toggle to disable language options until translations are complete
- [ x] `./precheck` was executed (Integration/Component/Unit tests)
- [x ] `sbt scalafmt test:scalafmt` was executed 
- [ x] No Accessibility errors/warnings reported by Wave
> PPTP-1843: Welsh translation toggle added to returns

- app/uk/gov/hmrc/plasticpackagingtax/returns/config/AppConfig.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/connectors/ObligationsConnector.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/connectors/TaxReturnsConnector.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/controllers/actions/AuthAction.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/controllers/actions/AuthAgentAction.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/controllers/actions/AuthCheckAction.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/controllers/agents/AgentsController.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/controllers/agents/SelectedClientIdentifier.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/controllers/home/UnauthorisedController.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/forms/CommonFormValidators.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/forms/agents/ClientIdentifier.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/models/request/JourneyAction.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/views/agents/agents_page.scala.html
- build.sbt
- conf/app.routes
- conf/application.conf
- conf/home.routes
- conf/messages.en
- test/uk/gov/hmrc/plasticpackagingtax/returns/base/MockAuthAction.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/base/PptTestData.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/base/unit/ControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/controllers/actions/AuthActionSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/controllers/agents/AgentsControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/controllers/bta/BtaEntryPointControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/controllers/home/UnauthorisedControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/controllers/subscriptions/ViewSubscriptionControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/forms/ClientIdentifierSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/views/agents/AgentsViewSpec.scala
Adjust AuthAction to allow agents to work with PPT accounts which they have been delegated access to.
TLDR - to auth as an Agent, you need to know the client's PPT identifier BEFORE calling auth,
This is different to the existing single user code with calls auth and then finds the PPT identifier in the auth response.
When auth'ing as an agent, the AuthAction might supply the PPT identifier of the account the agent is trying to access.
This has to be supplied as as a parameter to the auth call. 
This is different to the existing single user code which auths and then finds the PPT identifier from the enrolments in the auth response.
Add a new screen at `/agents` to prompt agents for the client identifier of their client.
This identifier is stashed on the MDTP session.
This screen is be …
> Enable Agents access to returns

- app/uk/gov/hmrc/plasticpackagingtax/returns/config/AppConfig.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/controllers/actions/AuthAction.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/controllers/actions/AuthAgentAction.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/controllers/actions/AuthCheckAction.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/controllers/actions/CommonAuth.scala
- conf/application.conf
- test/uk/gov/hmrc/plasticpackagingtax/returns/base/MockAuthAction.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/controllers/actions/AuthActionSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/controllers/actions/AuthAgentSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/controllers/actions/AuthCheckSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/controllers/agents/AgentsControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/controllers/home/UnauthorisedControllerSpec.scala
Returns front end requires strong credentials for consistency with Registration.
1 failing acceptance test looks unrelated.
> PPTP-1851 Returns sends signed in user for uplift if they do not have strong credentials

- app/uk/gov/hmrc/plasticpackagingtax/returns/controllers/actions/AuthAction.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/controllers/agents/AgentsController.scala
- app/uk/gov/hmrc/plasticpackagingtax/returns/controllers/home/UnauthorisedController.scala
- conf/messages.en
- test/uk/gov/hmrc/plasticpackagingtax/returns/controllers/agents/AgentsControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/returns/controllers/home/UnauthorisedControllerSpec.scala
Not enrolled landing page will pass a hint to the agents page via the Play flash message API
> PPTP-1853 Warn agents when the PPT identifier they have supplied fails auth

- app/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/confirmation_page.scala.html
We only have a regular AuthenticatedRequest when displaying the return submission confirmation page (as the temporary TaxReturn is now deleted). Since we have commented out sections which appear to need details from the submitted return we might need to make a call to pick up the submitted return from EIS/ETMP before displaying this page and passing this TaxReturn as a parameter to the page - we can fix this if and when it is needed.
> PPTP-1867 : Delete Successfully Submitted Tax Returns

- app/uk/gov/hmrc/plasticpackagingtax/returns/controllers/home/SignOutController.scala
- build.sbt
- test/uk/gov/hmrc/plasticpackagingtax/returns/controllers/home/SignOutControllerSpec.scala
Removes auth from the sign out end point on Returns.
This is consistent with Registration (but that's a weak argument which I'v e cherry picked) 
This allows agents who do not meet the enrolment predicate for accessing the actual journeys to gracefully give up and exit the platform from the returns UI.
Sign out appears to be an idempotent operation with no side effects.
Permitting this is deem safer that trying to create a special case auth action just for sign out.
> Sign out does not need to be authed

- app/uk/gov/hmrc/plasticpackagingtax/returns/views/home/home_page.scala.html
Fix missing manage registration link when de-reg feature disabled
> PPTP-1911: Fix missing manage registration link when de-reg feature disabled

- conf/messages.cy
Adding Welsh translations and placeholder fallback text.
/account
Before: 
After:
/account/not-enrolled
Before:
After (Go-Live):
> PPTP-1237 - Adding Welsh translations

- app/controllers/amends/SubmittedReturnsController.scala
- app/views/IndexView.scala.html
- app/views/amends/ViewReturnSummaryView.scala.html
- app/views/returns/SubmittedReturnsView.scala.html
- conf/messages.cy
- conf/messages.en
- test/controllers/returns/SubmittedReturnsControllerSpec.scala
- test/views/returns/SubmittedReturnsViewSpec.scala
- always show content for amending returns instead of behind feature switch
- amend using gform link open in same tab
> PPTP-2302: Always show amend content regardless of feature switch

- app/assets/stylesheets/_returns.scss
- app/views/amends/AmendManufacturedPlasticPackagingView.scala.html
- app/views/returns/ReturnsCheckYourAnswersView.scala.html
- project/AppDependencies.scala
Note I've put some styling in because since upgrading play-frontend-govuk the value in the check answers screen is breaking by character and displaying the text vertically 🫤
> PPTP-2384: Fix all Axe and VNU HTML validation errors

- app/viewmodels/checkAnswers/ViewReturnSummaryViewModel.scala
- app/viewmodels/checkAnswers/returns/ManufacturedPlasticPackagingSummary.scala
- app/views/returns/ReturnsCheckYourAnswersView.scala.html
- project/AppDependencies.scala
As agreed with design team.
1. Reduce the risk of overflow of column 2 into column 3 on check answers pages
2. Right align business info on final return summary
> PPTP-2448: Reduce key column width on check answers pages

- test/views/returns/StartYourReturnViewSpec.scala
we were using Localdate.now() therefore tests looking for 'July' test failed
> Patch: test data made static

- app/forms/changeGroupLead/MainContactJobTitleFormProvider.scala
- app/forms/changeGroupLead/MainContactNameFormProvider.scala
- app/viewmodels/checkAnswers/changeGroupLead/MainContactNameSummary.scala
- Updating regex pattern to block back ticks
- Removing html format escape to allow apostrophe to be displayed in cya
Note - Tested manually that js can not be executed in CYA page, had to hack the code to even allow the required chars to do that.
> PPTP-2760 - Updating CYA character encoding
